//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bloga.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public article()
        {
            this.comments = new HashSet<comment>();
            this.labels = new HashSet<label>();
        }
    
        public int ARTICLEID { get; set; }
        public string AHEADER { get; set; }
        public string ACONTENT { get; set; }
        public System.DateTime ADATE { get; set; }
        public int AVIEW { get; set; }
        public int ALIKE { get; set; }
        public int WRITERID { get; set; }
        public int CATEGORYID { get; set; }
        public int IMAGEID { get; set; }
    
        public virtual article_image article_image { get; set; }
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<label> labels { get; set; }
    }
}
