//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bloga.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int COMMENTID { get; set; }
        public string CCOMMENT { get; set; }
        public System.DateTime CDATE { get; set; }
        public string CNAME { get; set; }
        public string CLIKE { get; set; }
        public int ARTICLEID { get; set; }
    
        public virtual article article { get; set; }
    }
}
