//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bloga.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.user_role = new HashSet<user_role>();
            this.user1 = new HashSet<user>();
            this.users = new HashSet<user>();
        }
    
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string NAME { get; set; }
        public string LASTNAME { get; set; }
        public string USEREMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string BIO { get; set; }
        public Nullable<System.DateTime> DATEOFREGISTRATION { get; set; }
        public Nullable<int> IMAGEID { get; set; }
        public Nullable<bool> WRITER { get; set; }
        public Nullable<bool> APPROVED { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    
        public virtual article_image article_image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_role> user_role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
    }
}
